
async function boot(){const gate=document.getElementById('access-gate'),view=document.getElementById('view'),nav=document.querySelector('nav');let access=await fetch('/api/console',{credentials:'same-origin'});if(!access.ok){gate.hidden=false;document.getElementById('access-form').onsubmit=async e=>{e.preventDefault();const code=new FormData(e.target).get('code');const r=await fetch('/api/console',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'login',code})});if(r.ok)location.reload();else document.getElementById('access-error').textContent='That code was not accepted.'};return}gate.hidden=true;view.hidden=false;nav.hidden=false;window.__coachData=await access.json();return window.__coachData}
boot().then(()=>{
const PUBLIC='https://www.rtpny.com',MANIFEST=PUBLIC+'/content.json';
let plans=[['2026-09-01','Rowing 101 / Varsity Circuit','Erg setup, posture, sequence. Varsity: 25 min steady @ 18–20 + bodyweight/core.','Novices learn sequence; varsity completes quality work.'],['2026-09-02','Recovery Order / Varsity Circuit','Hands away → body over → slide. Varsity: 3 × 8 min @ 18–20.','Patient recovery and consistent rhythm.'],['2026-09-03','Connection / Varsity Circuit','Full stroke review, legs-first connection, then 3 × 5 min @ 18.','Connect the drive without rushing.'],['2026-09-04','Friday Team Day','Stadium steps or outdoor team challenge. No ergs.','Conditioning and team cohesion.'],['2026-09-17','2K #1','Standard warm-up, then 2K. Record each 500 split.','Establish an honest baseline.'],['2026-09-18','Rigging Day','Rig boats. Teach parts, hardware, care and ownership.','Make the fleet ready.'],['2026-09-21','Commands & Safety','Carrying, commands, launch sequence, stopping, turning and emergency basics.','Operate safely before rowing.'],['2026-09-22','First Water Practice','Set work, arms/body sequencing, pause work, short rowing @ 16–18.','Make the boat stable.'],['2026-10-24','Head of the Fish','Race day. Standard warm-up, 4K race plan, cooldown.','Execute the 4K.'],['2026-10-29','2K #2','Same warm-up as Sept. 17, then 2K. Record each 500 split.','Measure fall progress.'],['2026-11-07','Frostbite','Race day. Start-settle, base rhythm, attack third 500.','Execute the 2K plan.'],['2026-11-12','Final Practice','Light technical row if safe; otherwise easy movement + season review.','Close the fall intentionally.']];
let selectedSeason='Fall 2026',seasonPlans={};
const fallback=[['New Rower & Athlete Guide','First days, preparation, commands, expectations','athletes'],['Coaching Resources','Sequence, posture, recovery, connection, benchmarks','coaching'],['Regatta Hub','Race-day, travel, equipment, and family logistics','regattas'],['Parent Guide','What to expect, costs, forms, and support','parents'],['Safety & Equipment','Team movement, commands, fleet care, and readiness','safety'],['About the Program','Recruiting, alumni, leadership, and support','about']];
function normalize(items){return (items||[]).map(s=>[s.date,s.title,(s.workout||'')+' '+(s.land||''),s.intent,s.sessionType||'land',s.releaseTimes||{water:'05:00',land:'06:01'}])}const central=window.__coachData;if(central?.seasons){if(central.seasons['Fall 2026'])seasonPlans['Fall 2026']=normalize(central.seasons['Fall 2026'].sessions);if(central.seasons['Spring 2027'])seasonPlans['Spring 2027']=normalize(central.seasons['Spring 2027'].sessions);plans=seasonPlans['Fall 2026']||plans}else seasonPlans['Fall 2026']=plans;
let manifest={resources:fallback.map(x=>({title:x[0],summary:x[1],path:'#'+x[2]}))},active='today',weatherRequest=0;
function current(){let d=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());return plans.find(x=>x[0]===d)||null}function nextScheduled(){let d=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());return plans.find(x=>x[0]>d)||null}
function noteKey(date){return 'sbu-crew-coach-note-'+date}
function notes(date){return localStorage.getItem(noteKey(date))||''}
function resourceHref(x){return x.href||(x.path&&/^https?:/i.test(x.path)?x.path:PUBLIC+'/'+String(x.path||'').replace(/^\//,''))}
function card(p){return '<section class="card"><div class="ey">'+p[0]+'</div><div class="title">'+p[1]+'</div><span class="pill">'+(p[4]||'land').toUpperCase()+'</span><div class="section"><h3>WORKOUT</h3><p>'+p[2]+'</p></div><div class="section"><h3>FOCUS</h3><p>'+p[3]+'</p></div><div class="section"><h3>CUES</h3><div class="chips"><span class="chip">Move together</span><span class="chip">Long strokes</span><span class="chip">Trust the plan</span></div></div><div class="section"><h3>COACH NOTES</h3><textarea class="note" id="notes-'+p[0]+'" placeholder="Capture the adjustment you want to carry forward…">'+notes(p[0])+'</textarea><button class="save" id="save-'+p[0]+'">Save note</button></div></section>'}
function render(v=active){active=v;let seasonPicker=(v==='season'||v==='plan')?'<div class="section"><label for="season-choice"><h3>SEASON</h3></label><select id="season-choice" class="season-choice"><option>Fall 2026</option><option>Spring 2027</option></select></div>':'';let today=current(),next=nextScheduled(),i=today?plans.findIndex(x=>x[0]===today[0]):-1,p=v==='tomorrow'?plans[i>=0?Math.min(i+1,plans.length-1):0]:today,h=v==='today'&&!p?'<section class="card"><div class="ey">NO ORGANIZED PRACTICE</div><div class="title">No scheduled workout today.</div><p>'+(next?'Next scheduled: '+next[0]+' · '+next[1]+'.':'Check the annual schedule or coach notice for the next session.')+'</p></section>':v==='today'||v==='tomorrow'?card(p):v==='season'?'<section class="card"><div class="title">Fall 2026</div><p>Training progression and confirmed events. Historical material is context, not a current requirement.</p></section>'+plans.map(x=>'<section class="card"><div class="ey">'+x[0]+'</div><div class="title" style="font-size:20px">'+x[1]+'</div><p class="small">'+x[3]+'</p></section>').join(''):v==='plan'?'<section class="card"><div class="title">Daily Plan</div>'+plans.map(x=>'<details class="section"><summary><b>'+x[0]+' · '+x[1]+'</b></summary><p>'+x[2]+'</p><small>'+x[3]+'</small></details>').join('')+'</section>':'<section class="card"><div class="ey">LIVE FROM RTPNY.COM</div><div class="title">Resources</div><p>Curated public guidance for athletes, families, and coaches. The Coach App and public site use the same resource index.</p>'+manifest.resources.map(x=>'<a class="resource" href="'+resourceHref(x)+'" target="_blank" rel="noopener"><i>↗</i><strong>'+x.title+'</strong><span>'+x.summary+'</span></a>').join('')+'</section>';document.getElementById('view').innerHTML=seasonPicker+h;let seasonChoice=document.getElementById('season-choice');if(seasonChoice){seasonChoice.value=selectedSeason;seasonChoice.onchange=()=>{selectedSeason=seasonChoice.value;plans=seasonPlans[selectedSeason]||plans;render(active)}}document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v));let s=document.getElementById('save-'+(p&&p[0]));if(s)s.onclick=()=>{localStorage.setItem(noteKey(p[0]),document.getElementById('notes-'+p[0]).value);s.textContent='Saved';setTimeout(()=>s.textContent='Save note',1200)};weatherRequest++;document.querySelectorAll('#view .weather').forEach(e=>e.remove());if(v==='today'||v==='tomorrow')weather(v,weatherRequest)}
async function weather(v,request){try{let q=(await fetch('https://api.open-meteo.com/v1/forecast?latitude=40.9465&longitude=-73.0693&current=temperature_2m,wind_speed_10m,wind_gusts_10m,wind_direction_10m&wind_speed_unit=kn&temperature_unit=fahrenheit&timezone=America%2FNew_York').then(r=>r.json())).current;if(request!==weatherRequest||active!==v)return;let d=['N','NE','E','SE','S','SW','W','NW'][Math.round(q.wind_direction_10m/45)%8],lim={E:15,W:15,S:20,N:10,NE:10,NW:15,SE:15,SW:15}[d]||15,e=document.createElement('section');document.querySelectorAll('#view .weather').forEach(x=>x.remove());e.className='card weather '+(q.wind_speed_10m>lim||q.wind_gusts_10m>lim+7?'land':'go');e.innerHTML='<div class="ey">PORT JEFFERSON HARBOR · '+(v==='today'?'TODAY':'TOMORROW')+'</div><div class="status">'+(q.wind_speed_10m>lim||q.wind_gusts_10m>lim+7?'LAND PRACTICE':'WATER PRACTICE')+'</div><div class="metrics"><div class="metric"><b>'+Math.round(q.wind_speed_10m)+' kt</b><span>WIND</span></div><div class="metric"><b>'+Math.round(q.wind_gusts_10m)+' kt</b><span>GUST</span></div><div class="metric"><b>'+Math.round(q.temperature_2m)+'°</b><span>AIR</span></div><div class="metric"><b>'+d+'</b><span>DIRECTION</span></div></div>';document.getElementById('view').prepend(e)}catch(e){}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.v));document.querySelector('.edit').onclick=()=>{render('today');document.querySelector('.note')?.focus()};render();fetch(MANIFEST).then(r=>r.json()).then(x=>{if(x.resources?.length){manifest=x;render(active)}}).catch(()=>{});// Authenticated schedule data is loaded from the coach record.
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js');
});

