const PUBLIC='https://www.rtpny.com';
const state={plan:{season:'Fall 2026',phases:[],sessions:[]},content:{resources:[]},history:[],dirty:false};
let authCode='';
const $=s=>document.querySelector(s);
function setStatus(t){$('#save-state').textContent=t}
function setDirty(){state.dirty=true;setStatus('Unsaved changes')}
function value(el,key){return key==='custom'?el.value:el.value}
function bind(el,obj){el.querySelectorAll('[data-key]').forEach(input=>{let key=input.dataset.key;if(key==='custom')input.value=JSON.stringify(obj.custom||{},null,2);else input.value=obj[key]||'';input.addEventListener('input',()=>{if(key==='custom'){try{obj.custom=JSON.parse(input.value||'{}')}catch{}}else obj[key]=input.value;setDirty()})})}
function renderSessions(){const host=$('#sessions');host.innerHTML='';state.plan.sessions.forEach((s,i)=>{const node=$('#session-template').content.cloneNode(true),card=node.querySelector('.session-card');bind(card,s);card.querySelector('.remove').onclick=()=>{state.plan.sessions.splice(i,1);renderSessions();setDirty()};host.append(card)});$('#session-count').textContent=state.plan.sessions.length}
function renderContent(){const host=$('#content-records');host.innerHTML='';state.content.resources.forEach((r,i)=>{const card=document.createElement('article');card.className='content-record';card.innerHTML='<label>Title<input data-key="title"></label><label>Link / path<input data-key="href"></label><label>Summary<textarea data-key="summary"></textarea></label><button class="remove" type="button">Remove record</button>';bind(card,r);card.querySelector('.remove').onclick=()=>{state.content.resources.splice(i,1);renderContent();setDirty()};host.append(card)});$('#content-count').textContent=state.content.resources.length}
function renderHistory(){const host=$('#history');host.innerHTML=state.history.length?state.history.map(x=>`<div class="history-item"><span><b>${x.label}</b><br><small>${new Date(x.at).toLocaleString()}</small></span><span class="muted">${x.kind}</span></div>`).join(''):'<p class="muted">Versions appear after the first save.</p>'}
const authHeaders=()=>authCode?{'x-coach-code':authCode}: {};
async function load(){try{let r=await fetch('/api/console',{credentials:'same-origin',headers:authHeaders()});if(r.ok){let d=await r.json();if(d.plan){Object.assign(state,d);setStatus('Connected');return 'connected'}let [p,c]=await Promise.all([fetch('/training-plan.json').then(r=>r.json()),fetch(PUBLIC+'/content.json').then(r=>r.json())]);state.plan=p;state.content=c;setStatus('Connected · starting from current files');return 'connected'}if(r.status===401)return 'login'}catch{}let [p,c]=await Promise.all([fetch('/training-plan.json').then(r=>r.json()),fetch(PUBLIC+'/content.json').then(r=>r.json())]);state.plan=p;state.content=c;const draft=localStorage.getItem('coach-console-draft');if(draft)Object.assign(state,JSON.parse(draft));setStatus('Local draft mode');return 'local'}
function saveLocal(kind='Draft saved'){localStorage.setItem('coach-console-draft',JSON.stringify({plan:state.plan,content:state.content,history:state.history}));state.dirty=false;setStatus(kind)}
async function save(publish=false){setStatus(publish?'Publishing…':'Saving…');try{let r=await fetch('/api/console',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json',...authHeaders()},body:JSON.stringify({action:publish?'publish':'draft',plan:state.plan,content:state.content})});if(!r.ok)throw Error();Object.assign(state,await r.json());state.dirty=false;setStatus(publish?'Published':'Draft saved');renderHistory()}catch{saveLocal(publish?'Saved locally — connect storage to publish':'Saved locally')}}
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-error').textContent='';let body=Object.fromEntries(new FormData(e.target));try{let r=await fetch('/api/console',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'login',...body})});if(!r.ok)throw Error();authCode=body.code;const mode=await load();if(mode!=='login'){$('#login').hidden=true;$('#console').hidden=false;renderSessions();renderContent();renderHistory()}}catch{$('#login-error').textContent='That code was not accepted.'}};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==t.dataset.panel)});
$('#add-session').onclick=()=>{state.plan.sessions.push({date:'',title:'New session',block:'',intent:'',workout:'',cue:'',land:'',custom:{}});renderSessions();setDirty()};
$('#add-content').onclick=()=>{state.content.resources.push({title:'New resource',summary:'',href:'#'});renderContent();setDirty()};
$('#save').onclick=()=>save(false);$('#publish').onclick=()=>save(true);
(async()=>{const mode=await load();if(mode==='login'){$('#login').hidden=false;$('#console').hidden=true;setStatus('Sign in required');return}$('#login').hidden=true;$('#console').hidden=false;renderSessions();renderContent();renderHistory()})().catch(()=>{$('#login').hidden=false;$('#console').hidden=true;setStatus('Sign in required')});

