const { put, get } = require('@vercel/blob');
const crypto=require('crypto');
const cookie='coach_console_session';const loginAttempts=new Map();function clientKey(req){return String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim()}function limited(req){const key=clientKey(req),now=Date.now(),old=loginAttempts.get(key);if(!old||now-old.started>900000){loginAttempts.set(key,{started:now,count:0});return false}return old.count>=8}
function sign(v){if(!process.env.CONSOLE_SESSION_SECRET)return '';return crypto.createHmac('sha256',process.env.CONSOLE_SESSION_SECRET).update(v).digest('hex')}
function authorized(req){if(!process.env.CONSOLE_SESSION_SECRET||!process.env.CONSOLE_CODE)return false;if(req.headers['x-coach-code']===process.env.CONSOLE_CODE)return true;const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookie+'='));if(!raw)return false;const [v,s]=decodeURIComponent(raw.slice(cookie.length+1)).split('.');return v&&s===sign(v)&&Number(v.split(':').slice(1).join(':'))>Date.now()}
function json(res,status,body,headers={}){res.statusCode=status;Object.entries({'content-type':'application/json','access-control-allow-origin':'https://www.rtpny.com','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'content-type,x-coach-code',...headers}).forEach(([k,v])=>res.setHeader(k,v));res.end(JSON.stringify(body))}
async function readBlob(pathname){const result=await get(pathname,{access:'private'});if(!result||!result.stream)return null;return new Response(result.stream).json()}
module.exports=async(req,res)=>{try{
 if(req.method==='GET'){const view=new URL(req.url,'https://localhost').searchParams.get('view');if(view==='published'){const data=await readBlob('coach-content/published.json');return data?json(res,200,{content:data.content,controls:data.controls||{}}):json(res,404,{error:'not published'})}if(view==='athlete'){const data=await readBlob('coach-content/published.json');if(!data)return json(res,404,{error:'not published'});const sessions=Object.values(data.seasons||{}).flatMap(x=>x?.sessions||[]).sort((a,b)=>String(a.date).localeCompare(String(b.date)));const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());const session=sessions.find(x=>x.date===today)||null;const next=sessions.find(x=>x.date>today)||null;const safe=x=>x?{date:x.date,title:x.title,block:x.block,intent:x.intent,workout:x.workout,cue:x.cue,land:x.land,sessionType:x.sessionType||'land',releaseTimes:x.releaseTimes||{water:'05:00',land:'06:01'}}:null;return json(res,200,{date:today,session:safe(session),nextSession:safe(next)})}if(!authorized(req))return json(res,401,{error:'unauthorized'});const data=await readBlob('coach-content/draft.json');if(data)return json(res,200,data);return json(res,200,{plan:null,content:null,history:[]})}
 let body=req.body||await new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}})});
 if(body.action==='login'){if(limited(req))return json(res,429,{error:'too many attempts'});if(/^\d{6}$/.test(body.code||'')&&body.code===process.env.CONSOLE_CODE&&process.env.CONSOLE_SESSION_SECRET){loginAttempts.delete(clientKey(req));const v=`coach:${Date.now()+86400000}`;return json(res,200,{ok:true},{'set-cookie':[`${cookie}=${encodeURIComponent(v+'.'+sign(v))}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=86400`]})}return json(res,401,{error:'unauthorized'})}
 if(!authorized(req))return json(res,401,{error:'unauthorized'});
 if(body.action==='draft'||body.action==='publish'){const now=new Date().toISOString(),data={plan:body.plan,seasons:body.seasons||{[body.plan?.season||'Fall 2026']:body.plan},content:body.content,controls:body.controls||{},history:[{label:body.action==='publish'?'Published season':'Saved draft',at:now,kind:body.action},...(body.history||[])].slice(0,20)};await put(`coach-content/${body.action==='publish'?'published':'draft'}.json`,JSON.stringify(data),{access:'private',addRandomSuffix:false});return json(res,200,data)}
 return json(res,400,{error:'unknown action'});
 }catch(e){return json(res,500,{error:'console unavailable'})}}

