const { put, get } = require('@vercel/blob');
function json(res,status,body,headers={}){res.statusCode=status;Object.entries({'content-type':'application/json','access-control-allow-origin':'https://www.rtpny.com','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'content-type',...headers}).forEach(([k,v])=>res.setHeader(k,v));res.end(JSON.stringify(body))}
async function readBlob(pathname){const result=await get(pathname,{access:'private'});if(!result||!result.stream)return null;return new Response(result.stream).json()}
module.exports=async(req,res)=>{try{
 if(req.method==='GET'){const view=new URL(req.url,'https://localhost').searchParams.get('view');if(view==='published'){const data=await readBlob('coach-content/published.json');return data?json(res,200,{content:data.content,controls:data.controls||{}}):json(res,404,{error:'not published'})}if(view==='athlete'){const data=await readBlob('coach-content/published.json');if(!data)return json(res,404,{error:'not published'});const sessions=Object.values(data.seasons||{}).flatMap(x=>x?.sessions||[]).sort((a,b)=>String(a.date).localeCompare(String(b.date)));const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value])),today={date:parts.year+'-'+parts.month+'-'+parts.day,minutes:Number(parts.hour)*60+Number(parts.minute)},session=sessions.find(x=>x.date===today.date)||null,next=sessions.find(x=>x.date>today.date)||null,releaseMode=x=>x?.practiceStatus==='water'||x?.practiceStatus==='land'?x.practiceStatus:x?.sessionType==='water'?'water':'land',released=x=>{if(!x||x.date!==today.date)return false;const mode=releaseMode(x),time=x?.releaseTimes?.[mode]||(mode==='water'?'05:00':'06:01'),[hour,minute]=time.split(':').map(Number);return today.minutes>=hour*60+minute},safe=(x,full)=>{if(!x)return null;const base={date:x.date,title:x.title,block:x.block,intent:x.intent,sessionType:x.sessionType||'land',releaseTimes:x.releaseTimes||{water:'05:00',land:'06:01'},practiceStatus:x.practiceStatus||'forecast'};return full&&x.practiceStatus!=='canceled'?Object.assign(base,{workout:x.workout,cue:x.cue,land:x.land}):base};return json(res,200,{date:today.date,coachPreview:false,session:safe(session,released(session)),nextSession:safe(next,false)})}const data=await readBlob('coach-content/draft.json');if(data)return json(res,200,data);return json(res,200,{plan:null,content:null,history:[]})}
 let body=req.body||await new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}})});
 if(body.action==='login')return json(res,200,{ok:true});
 if(body.action==='draft'||body.action==='publish'){const now=new Date().toISOString(),data={plan:body.plan,seasons:body.seasons||{[body.plan?.season||'Fall 2026']:body.plan},content:body.content,controls:body.controls||{},teamOps:body.teamOps||{},history:[{label:body.action==='publish'?'Published season':'Saved draft',at:now,kind:body.action},...(body.history||[])].slice(0,20)};await put(`coach-content/${body.action==='publish'?'published':'draft'}.json`,JSON.stringify(data),{access:'private',addRandomSuffix:false,allowOverwrite:true});return json(res,200,data)}
 return json(res,400,{error:'unknown action'});
 }catch(e){return json(res,500,{error:'console unavailable'})}}

